# Generated by Django 6.0.7 on 2026-07-07 16:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('3d_art', '3D Art'), ('graphic_design', 'Graphic Design')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('token_artist', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('token_client', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_creare', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('extra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reject', 'Reject'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('project_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='projects.projectcategory')),
            ],
        ),
    ]
