# Generated by Django 6.0.7 on 2026-07-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_changerequest_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='draft_image',
            field=models.ImageField(blank=True, null=True, upload_to='drafts/'),
        ),
    ]
