# Generated by Django 6.0.7 on 2026-07-14 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_changerequest_draft_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changerequest',
            name='draft_image',
        ),
        migrations.CreateModel(
            name='DraftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='drafts/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_images', to='projects.project')),
            ],
        ),
    ]
