# Generated by Django 6.0.7 on 2026-07-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_changerequest_draft_image_draftimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
