# Generated by Django 6.0.7 on 2026-07-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_estimated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='artist_note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
