# Generated by Django 6.0.7 on 2026-07-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_changerequest_artist_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
