# Generated by Django 6.0.7 on 2026-07-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_backfill_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
