# Generated by Django 6.0.7 on 2026-07-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_projectcategory_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('reject', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=20),
        ),
    ]
