# Generated by Django 6.0.7 on 2026-07-20 17:52

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_changerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftimage',
            name='image',
            field=models.ImageField(upload_to=projects.models.draft_image_upload_to),
        ),
    ]
