# Generated by Django 6.0.7 on 2026-07-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('3d_art', '3D Art'), ('2d_art', '2D Art'), ('graphic_design', 'Graphic Design'), ('web_design', 'Web Design'), ('video_editing', 'Video Editing')], max_length=50),
        ),
    ]
